# Generated by Django 3.2 on 2021-12-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_roadleader', models.BooleanField(default=False)),
                ('sex', models.BooleanField()),
                ('belongs', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fleetleader',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.BooleanField()),
                ('hasfleet', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Motorcade',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Motors',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('seats', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('drivername', models.CharField(max_length=255)),
                ('driverID', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('carID', models.CharField(max_length=255)),
                ('station', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('belongs', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('belongs', models.CharField(max_length=255)),
            ],
        ),
    ]
