# Generated by Django 3.2 on 2021-12-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_punishment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punishment',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
